server:
  port: 9070

spring:
  application:
    name: api-gateway-service

zuul:
  routes:
    multimedia:
      path: /services/multimedia/**
      serviceId: multimedia-service
      
    posts:
      path: /services/posts/**
      serviceId: posts-service
      
    users:
      path: /services/users/**
      serviceId: users-service